### List all messages
GET http://localhost:3000/messages

### Create a new message
POST http://localhost:3000/messages
content-type: application/json

{
  "content": "this is a test message"
}

### Get a particular message
GET http://localhost:3000/messages/921
